# Generated by Django 4.2.5 on 2023-09-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twaaku_app', '0003_alter_deposit_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='user',
            new_name='employee',
        ),
    ]
