# Generated by Django 4.2.5 on 2023-09-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twaaku_app', '0004_rename_user_deposit_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_responsible',
            new_name='person_responsible',
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('date_of_purchase', models.DateTimeField()),
                ('receipt', models.ImageField(blank=True, upload_to='deposits/%Y/%m/%d')),
                ('person_responsible', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='twaaku_app.employee')),
            ],
        ),
    ]
