# Generated by Django 4.2.5 on 2023-09-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twaaku_app', '0005_rename_user_responsible_expense_person_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.CharField(choices=[('Nateete', 'Nateete'), ('kisenyi', 'kisenyi'), ('Kikajjo', 'Kikajjo'), ('Other', 'Other')], default='Nateete', max_length=200),
        ),
        migrations.AddField(
            model_name='purchase',
            name='branch',
            field=models.CharField(choices=[('Nateete', 'Nateete'), ('kisenyi', 'kisenyi'), ('Kikajjo', 'Kikajjo'), ('Other', 'Other')], default='Nateete', max_length=200),
        ),
    ]
