# Generated by Django 4.2.5 on 2023-09-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twaaku_app', '0006_expense_branch_purchase_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_of_expense',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='date_of_income',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_of_purchase',
            field=models.DateField(),
        ),
    ]
