# Generated by Django 4.2.5 on 2023-09-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twaaku_app', '0007_alter_expense_date_of_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherincome',
            name='person_responsible',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='twaaku_app.employee'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.CharField(choices=[('Nateete', 'Nateete'), ('kisenyi', 'kisenyi'), ('Kikajjo', 'Kikajjo'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='branch',
            field=models.CharField(choices=[('Nateete', 'Nateete'), ('kisenyi', 'kisenyi'), ('Kikajjo', 'Kikajjo'), ('Other', 'Other')], max_length=200),
        ),
    ]
