# Generated by Django 4.2.5 on 2023-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twaaku_app', '0009_remove_otherincome_person_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='receipt_no',
            field=models.CharField(default=1234, max_length=300),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='added_by',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='branch',
            field=models.CharField(choices=[('Nateete', 'Nateete'), ('kisenyi', 'kisenyi'), ('Kikajjo', 'Kikajjo'), ('Other', 'Other')], max_length=30),
        ),
    ]
