# Generated by Django 4.2.5 on 2023-09-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twaaku_app', '0010_purchase_receipt_no_alter_otherincome_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='parent_name',
            field=models.CharField(default='dad', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='parent_telephone',
            field=models.PositiveIntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='receipt_no',
            field=models.CharField(max_length=300),
        ),
    ]
